---

- name: Reload Systemd
  systemd:
    daemon_reload: yes

- name: Restart Systemd local fs target
  service:
    name: local-fs.target
    state: restarted

- name: Restart memcached
  service:
    name: memcached
    state: restarted
