---

# Unfortunately, the standard command to restart the service does not work in my tests.
# I filled this bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911483

- name: Stop fwknop server
  shell: >-
    pidof /usr/sbin/fwknopd
    && kill `pidof /usr/sbin/fwknopd`

- name: Restart fwknop server
  service:
    name: fwknop-server
    state: restarted

- name: Restart AppArmor service
  service:
    name: apparmor
    state: restarted
