---

################################################################################
# Get the external IP address, from configuration file,
# or automatically through a script

################################################################################
# Get the external IP address automatically first

- name: Get the external IP address automatically
  when: network.auto_detect_ip == "auto"
  include_tasks: auto-ip.yml

- name: Get the external IP address automatically
  when: network.auto_detect_ip != "auto"
  include_tasks: manual-ip.yml

# Detect the main IP address type (IPv4 or IPv6)
- name: Detect the external IP address type (IPv4 or IPv6 / A or AAAA)
  tags: facts
  register: main_ip_type
  shell:
    echo {{ external_ip }}
    | grep -c ':' 2>&1 >/dev/null
    && echo AAAA || echo A

- name: Store the external IP address type detected
  tags: facts
  set_fact:
    external_ip_type: '{{ main_ip_type.stdout }}'

# Detect the backup IP address type (IPv4 or IPv6)
- name: Set backup IP address type (A or AAAA)
  when: network.backup_ip != None
  tags: facts
  register: backup_ip_type
  shell:
    echo {{ backup_ip }}
    | grep -c ':' 2>&1 >/dev/null
    && echo AAAA || echo A

- name: Set backup IP address type (A or AAAA)
  tags: facts
  when: network.backup_ip != None
  set_fact:
    backup_ip_type: '{{ backup_ip_type.stdout }}'
