---
# Manual IP specification

# First IP address
- name: Store the extenal IP address specified manually
  tags: facts
  set_fact:
    external_ip: '{{ network.external_ip }}'

# Backup IP address
- name: Get the backup IP address specified manually
  tags: facts
  set_fact:
    backup_ip: '{{ network.backup_ip }}'
