---

- name: Uninstall roundcube webmail
  tags: roundcube
  apt:
    name: "{{ pkgs }}"
    state: absent
    purge: yes
  vars:
    pkgs:
      - roundcube-pgsql
      - roundcube-core
      - roundcube-plugins
      - roundcube-plugins-extra
      - roundcube

- name: Remove roundcube nginx configuration
  tags: roundcube
  file:
    path: '{{ path }}'
    state: absent
  with_items:
    - '/etc/nginx/sites-available/webmail.{{ network.domain }}.conf'
    - '/etc/nginx/sites-enabled/webmail.{{ network.domain }}.conf'
  loop_control:
    loop_var: path

- name: Remove the roundcube configuration directory
  tags: roundcube
  file:
    path: /etc/roundcube
    state: absent

# AppArmor configuration ======================================================

- name: Remove nginx AppArmor profile
  notify:
    - Activate AppArmor profile
    - Restart AppArmor service
    - Restart nginx
  file:
    path: /etc/apparmor.d/local/roundcube
    state: absent

- name: Remove roundcube AppArmor specific configuration
  notify:
    - Activate AppArmor profile
    - Restart AppArmor service
    - Restart nginx
  lineinfile:
    path: /etc/apparmor.d/usr.sbin.nginx
    line: '  #include <local/roundcube>'
    state: absent
