---

# Uninstall roundcube
- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/../../config/defaults.yml'
  vars:
    certificate:
      type: webmail
  roles:
    - certificates
    - roundcube
