---

- name: Get the certificates list
  register: certs
  find:
    path: '/etc/letsencrypt/archive/{{ cert_dir }}'
    recurse: yes
    patterns: 'cert*,chain*,fullchain*'

- name: Get the keys list
  register: keys
  find:
    path: '/etc/letsencrypt/archive/{{ cert_dir }}'
    recurse: yes
    patterns: 'privkey*'

# Posix permissions

- name: Set the unix mode for the certificate files readable by root only
  tags: cert
  file:
    path: '{{ file.path }}'
    owner: root
    group: root
    mode: '0600'
  with_items:
    - '{{ certs.files }}'
    - '{{ keys.files }}'
  loop_control:
    loop_var: file

- name: Set the unix mode for the directory accessible by root only
  tags: cert
  file:
    path: '{{ dir }}'
    owner: root
    group: root
    mode: '0700'
  with_items:
      - '/etc/letsencrypt/archive/{{ cert_dir }}'
      - '/etc/letsencrypt/live/{{ cert_dir }}'
  loop_control:
    loop_var: dir

- name: Set the acl permissions for the directory
  tags: cert
  acl:
    path: '{{ path }}'
    entity: '{{ entity_group }}'
    etype: user
    permissions: 'rx'
    recursive: false
    state: present
    recalculate_mask: mask
  with_items:
      - '/etc/letsencrypt/archive/{{ cert_dir }}'
      - '/etc/letsencrypt/live/{{ cert_dir }}'
  loop_control:
    loop_var: path

- name: Set the acl for the files
  tags: cert
  acl:
    path: '{{ file.path }}'
    etype: user
    entity: '{{ entity_group }}'
    state: present
    permissions: 'r'
    recalculate_mask: mask
  with_items:
    - '{{ certs.files }}'
    - '{{ keys.files }}'
  loop_control:
    loop_var: file
