---

- name: Get the certificates list
  register: certs
  find:
    path: '/etc/letsencrypt/archive/{{ cert_dir }}'
    recurse: yes
    patterns: 'cert*,chain*,fullchain*'

- name: Get the keys list
  register: keys
  find:
    path: '/etc/letsencrypt/archive/{{ cert_dir }}'
    recurse: yes
    patterns: 'privkey*'

# Posix permissions: files should be readable, by default, only by root.
# The ACL will extend this to other daemons
- name: Set the unix mode for the certificate files readable by root only
  tags: cert
  file:
    path: '{{ file.path }}'
    owner: root
    group: root
    mode: '0600'
  with_items:
    - '{{ certs.files }}'
    - '{{ keys.files }}'
  loop_control:
    loop_var: file

# Anyone should be able to enter the directory, the files are protected
# by the step above.
# For the default ACL in the next step, we will not use 'x' to avoid
# new certificates being marked as executables, albeit this is harmless.
- name: Set the unix mode for the directory to be world readable
  tags: cert
  file:
    path: '{{ dir }}'
    owner: root
    group: root
    mode: '0755'
  with_items:
      - '/etc/letsencrypt/archive/{{ cert_dir }}'
      - '/etc/letsencrypt/live/{{ cert_dir }}'
  loop_control:
    loop_var: dir

# Now, we set the default acl for this directory: new certificates
# will be automatically marked as readable by the entity
- name: Set the acl and default acl permissions for the directory
  tags: cert
  acl:
    path: '{{ path }}'
    entity: '{{ entity_group }}'
    etype: user
    permissions: 'r'
    recursive: false
    state: present
    default: true
  with_items:
      - '/etc/letsencrypt/archive/{{ cert_dir }}'
      - '/etc/letsencrypt/live/{{ cert_dir }}'
  loop_control:
    loop_var: path

# Finally, we set the existing certificates ACLs to be readable by
# the entity. This is crucial, especially when restoring certificates
- name: Set the acl for the files
  tags: cert
  acl:
    path: '{{ file.path }}'
    etype: user
    entity: '{{ entity_group }}'
    state: present
    permissions: 'r'
  with_items:
    - '{{ certs.files }}'
    - '{{ keys.files }}'
  loop_control:
    loop_var: file
