---

- name: Uninstall privoxy
  tags: apt
  apt:
    name: privoxy
    state: absent
    purge: yes

- name: Remove firewall rules
  ufw:
    rule: allow
    proto: tcp
    port: '{{ privoxy.port }}'
    comment: Privoxy proxy server
    src: '{{ src }}'
    direction: in
    delete: yes
  with_items:
      - '{{ privoxy.accept_from }}'
  loop_control:
    loop_var: src

- name: Remove folders
  file:
    path: '{{ path }}'
    state: absent
  with_items:
      - /etc/privoxy
      - /var/log/privoxy
  loop_control:
    loop_var: path

# AppArmor configuration ======================================================

- name: Remove nginx AppArmor profile
  when: security.app_armor
  notify: Restart AppArmor service
  file:
    path: /etc/apparmor.d/usr.sbin.privoxy
    state: absent

