---

- name: Use the default domain name for FQDN
  when: certificate.type == '@'
  tags: cert
  set_fact:
    certificate_fqdn: "{{ network.domain }}"

- name: Create the certificate fqdn with the subdomain
  when: certificate.type != '@'
  tags: cert
  set_fact:
    certificate_fqdn: "{{ certificate.type }}.{{ network.domain }}"

# The certbot package need to be installed
- name: Remove the certificate directories
  file:
    path: '{{ path }}'
    state: absent
  with_items:
    - "/etc/letsencrypt/live/{{ certificate_fqdn }}"
    - "/etc/letsencrypt/archive/{{ certificate_fqdn }}"
    - "/etc/letsencrypt/renewal/{{ certificate_fqdn }}.conf"
  loop_control:
    loop_var: path

- name: Remove nginx configuration
  tags: nginx
  file:
    path: '{{ path }}'
    state: absent
  with_items:
    - '/etc/nginx/sites-available/{{ certificate_fqdn }}-cert.conf'
    - '/etc/nginx/sites-enabled/{{ certificate_fqdn }}-cert.conf'
  loop_control:
    loop_var: path

# AppArmor configuration ======================================================

- name: Remove web site AppArmor profile
  tags: security, apparmor
  file:
    path: "/etc/apparmor.d/local/nginx-{{ certificate_fqdn }}"
    state: absent

- name: Remove website AppArmor specific configuration
  register: aa_config
  tags: security, apparmor
  lineinfile:
    path: /etc/apparmor.d/usr.sbin.nginx
    line: '  #include <local/nginx-{{ certificate_fqdn }}>'
    insertbefore: '# End of local includes for homebox'
    state: absent

- name: Activate AppArmor profiles
  notify: Restart nginx
  when: aa_config.changed
  tags: security, apparmor
  command: 'aa-enforce usr.sbin.nginx'

# Remove certificates archive =================================================
- name: Delete the certificates from your local machine
  when: system.devel
  tags: cert,sync
  synchronize:
    mode: pull
    src: /etc/letsencrypt
    dest: '{{ playbook_dir }}/../../backup/{{ network.domain }}/certificates/'
    perms: yes
    delete: true
    rsync_opts:
      - '--no-motd'
      - '--exclude=readme.md'
      - '--update'
