---

- name: Post login script to check access, and log IP addresses and country
  tags: scripts
  copy:
    src: '{{ script.name }}.sh'
    dest: '/etc/dovecot/login-scripts/{{ script.order }}-{{ script.name }}'
    mode: '0755'
  with_items:
    - name: access-check-country
      order: 10
    - name: access-log
      order: 99
  loop_control:
    loop_var: script
