---

- name: Initialise the master user password parameters
  tags: impersonate
  set_fact:
    master_password_params: "{{ playbook_dir }}/../../backup/{{ network.domain }}/ldap/master.pwd {{ policies.system.password }}"

- name: Create the master user account password
  tags: impersonate
  set_fact:
    master_password: '{{ lookup("password", master_password_params) }}'

- name: Store the master user account password
  tags: impersonate
  htpasswd:
    path: /etc/dovecot/master-users
    name: '{{ mail.impersonate.master }}'
    password: '{{ master_password }}'
    owner: dovecot
    group: dovecot
    mode: '0400'
    crypt_scheme: ldap_sha1

