---

# Install automatic configuration for Mozilla Thunderbird
- hosts: homebox
  vars:
    redirect: true
    certificate:
      type: autoconfig
  roles:
    - role: certificates
      tags: certificates
    - autoconfig
