---

# Set up the autodiscover feature for Microsoft outlook
- hosts: homebox
  vars:
    certificate:
      type: autodiscover
  roles:
    - role: certificates
      tags: certificates
    - autodiscover
