---

# Install and configure the borgbackup package

# The ssh-keygen role generate an SSH key to use with ssh and sshfs
# remote repositories.
# Copy the public key on the remote backup location.

# If you redefine the user, the account should have full read access to /home
# and its subdirectories.

# As the key is going to be loaded non interactively and restricted to run borg
# it does not make sense to add a passphrase.

- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/../../config/defaults.yml'
  vars:
    key:
      path: '{{ backup.key.path }}'
      user: '{{ backup.key.user }}'
      comment: '{{ backup.key.comment }}'
      passphrase: ~
      name: '{{ backup.key.name }}'
      type: '{{ backup.key.type }}'
      size: '{{ backup.key.size }}'
  roles:
    - ssh-keygen
    - borg-backup
