---

# Create the default certificate for the jabber server
- hosts: homebox
  vars:
    redirect: true
    certificate:
      type: '@'
  roles:
    - role: certificates
      tags: certificates

# When using http download, also create a specific certificate
# to serve files over https (e.g. xmpp.homebox.space)
- hosts: homebox
  vars:
    certificate:
      type: 'xmpp'
  roles:
    - role: certificates
      tags: certificates

# Chat rooms behind a certificate
- hosts: homebox
  vars:
    certificate:
      type: conference
  roles:
    - role: certificates
      tags: certificates

# Install a ejabberd (https://docs.ejabberd.im)
- hosts: homebox
  roles:
    - ejabberd
