---

# Install Gogs git server
- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/../../config/defaults.yml'
  vars:
    redirect: true
    certificate:
      type: gogs
  roles:
    - role: certificates
      tags: certificates
    - role: gogs
      tags: gogs
