---

# Use Hugo for the main site (https://gohugo.io/)
- hosts: homebox
  vars:
    redirect: true
    certificate:
      type: www
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/../../config/defaults.yml'
  roles:
    - role: certificates
      tags: certificates
    - role: hugo
      tags: site
