---

# Install Jenkins for CI/CD
- hosts: homebox
  vars:
    redirect: true
    certificate:
      type: jenkins
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/../../config/defaults.yml'
    - '{{ playbook_dir }}/roles/roundcube/variables/main.yml'
  roles:
    - certificates
    - jenkins
