---

# Deploy the mta-sts certificate
- hosts: homebox
  vars:
    redirect: true
    certificate:
      type: mta-sts
      redirect: false
  roles:
    - role: certificates
      tags: certificates
    - role: mta-sts
      tags: mta-sts
