---

# Install a basic webmail (roundcube)
- hosts: homebox
  vars:
    redirect: true
    certificate:
      type: webmail
  roles:
    - role: certificates
      tags: certificates
    - imapproxy
    - roundcube
