---

# Install Sogo sute
- hosts: homebox
  vars:
    redirect: true
    certificate:
      type: sogo
  roles:
    - role: certificates
      tags: certificates
    - role: imapproxy
      tags: imapproxy
    - role: sogo
      tags: sogo
