---

# Install Transmission bittorrent daemon
- hosts: homebox
  vars:
    redirect: true
    certificate:
      type: transmission
  roles:
    - role: certificates
      tags: certificates
    - transmission
