---

# Install a basic web site in http and https
- hosts: homebox
  vars:
    redirect: true
    certificate:
      type: www
  roles:
    - role: certificates
      tags: certificates

- hosts: homebox
  vars:
    redirect: true
    certificate:
      type: '@'
  roles:
    - role: certificates
      tags: certificates

- hosts: homebox
  roles:
    - role: website-simple
      tags: website
