---

# Create well-known services for SOGo / etc.
# See: https://en.wikipedia.org/wiki/List_of_%2F.well-known%2F_services_offered_by_webservers

- hosts: homebox
  vars:
    redirect: true
    certificate:
      type: '@'
  roles:
    - role: certificates
      tags: certificates
    - well-known-services
