---

# Create a certificate for Zabbix
- hosts: homebox
  vars:
    redirect: true
    certificate:
      type: zabbix
  roles:
    - role: certificates
      tags: certificates
    - php-fpm
    - zabbix-server
