---

- name: Install privoxy
  apt:
    name: privoxy
    state: present

- name: Save original privoxy configuration
  copy:
    src: /etc/privoxy/config
    dest: /etc/privoxy/config-default
    remote_src: true

- name: Create the local configuration directory if it does not exists
  delegate_to: localhost
  file:
    path: '{{ playbook_dir }}/../../backup/{{ network.domain }}/privoxy/'
    state: directory

- name: Deploy custom user.filter and user.action if they exists
  synchronize:
    src: '{{ playbook_dir }}/../../backup/{{ network.domain }}/privoxy/'
    dest: /etc/privoxy
    owner: no
    group: no
    perms: yes
    rsync_opts:
      - '--no-motd'
      - '--update'
      - '--exclude=*.*'
      - '--include=*.action'
      - '--include=*.filter'

- name: Copy configuration
  tags: config
  notify: Restart privoxy
  template:
    src: privoxy.conf
    dest: /etc/privoxy/config

- name: Allow proxy access from LAN
  ufw:
    rule: allow
    proto: tcp
    port: '{{ privoxy.port }}'
    comment: Privoxy proxy server
    src: '{{ src }}'
    direction: in
  with_items:
      - '{{ privoxy.accept_from }}'
  loop_control:
    loop_var: src

- name: Activate the privoxy AppArmor profile
  when: security.app_armor
  register: aa_template
  tags: security, apparmor
  notify: Restart AppArmor service
  template:
    src: 'apparmor-privoxy'
    dest: '/etc/apparmor.d/usr.sbin.privoxy'

- name: Activate AppArmor profiles
  when: security.app_armor and aa_template.changed
  tags: dovecot, security, apparmor
  notify: Restart AppArmor service
  command: 'aa-enforce usr.sbin.privoxy'

- name: Run tasks for automatic easyrules update
  when: privoxy.adblock_rules.install
  tags: auto-update
  include_tasks: add-adblock-rules.yml

- name: Get custom user.filter and user.action on the local machine
  synchronize:
    src: /etc/privoxy
    dest: '{{ playbook_dir }}/../../backup/{{ network.domain }}/'
    mode: pull
    owner: no
    group: no
    perms: yes
    rsync_opts:
      - '--no-motd'
      - '--update'
      - '--exclude=*.*'
      - '--include=*.action'
      - '--include=*.filter'
