---

# Generate additional certificates
- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../config/system.yml'
    - '{{ playbook_dir }}/../config/defaults.yml'
  roles:
    - role: load-defaults
      tags: always
    - role: extra-certs
      tags: certificates
