---

# Initialise the packages repository to a standard,
# including backports, contrib and non-free software
- name: Initialise default repositories
  register: repositories
  tags: apt
  template:
    src: sources.list
    dest: /etc/apt/sources.list

- name: Update packages repositories
  register: packages_cache
  tags: apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade the distribution
  when: packages_cache.changed
  tags: apt
  apt:
    upgrade: yes

- name: Install apticron to send email alerts
  tags: apt
  apt:
    name: apticron
    state: latest

- name: Configure apticron to send email alerts
  tags: apt
  replace:
    path: /etc/apticron/apticron.conf
    regexp: '^#?EMAIL=".*"'
    replace: 'EMAIL="{{ security.alerts_email }}"'
