---

- name: Install packages to send alerts
  when: ejabberd.install
  tags: apt
  apt:
    name: sendxmpp
    state: present

- name: Deploy the global configuration file for access check settings
  tags: config
  template:
    src: access-check.cf
    dest: /etc/homebox/access-check.conf
    mode: 640

- name: Create the customconfiguration directory for the user
  file:
    path: '/home/users/{{ user.uid }}/.config/homebox'
    owner: '{{ user.uid }}'
    group: users
    state: directory
    recurse: true
  with_items:
    - '{{ users }}'
    - uid: postmaster
  loop_control:
    loop_var: user

- name: Copy the configuration file in each user directory
  template:
    src: access-check.cf
    dest: '/home/users/{{ user.uid }}/.config/homebox/access-check.conf'
    owner: '{{ user.uid }}'
    group: users
  with_items:
    - '{{ users }}'
    - uid: postmaster
  loop_control:
    loop_var: user

- name: Comment out the entries
  replace:
    path: '/home/users/{{ user.uid }}/.config/homebox/access-check.conf'
    regexp: '(^[A-Z].*)'
    replace: '# \1'
  with_items:
    - '{{ users }}'
    - uid: postmaster
  loop_control:
    loop_var: user

