---

roundcube_plugins:
  - password
  - archive
  - jqueryui
  - markasjunk
  - newmail_notifier
  - autologon
  - subscriptions_option
  - emoticons
  - new_user_identity
  - managesieve
  - contextmenu
  - thunderbird_labels
  - keyboard_shortcuts

# Available plugins:
# - dkimstatus
# - hide_blockquote
# - enigma
# - zipdownload
# - new_user_dialog
# - additional_message_headers
# - acl
# - database_attachments
# - debug_logger
# - filesystem_attachments
# - help
# - hide_blockquote
# - http_authentication
# - show_additional_headers
# - squirrelmail_usercopy
# - userinfo
# - vcard_attachments
# - virtuser_file
# - virtuser_query
#  - fail2ban

roundcube_packages:
  - postgresql
  - roundcube-pgsql
  - roundcube-core
  - roundcube-plugins
  - roundcube-plugins-extra
  - roundcube
  - imapproxy
  - php-fpm
  - php-ldap
  - php-net-sieve
  - php-net-ldap2
  - php-net-ldap3       # For LDAP address book
  - php7.0-pspell       # For spell checking
  - aspell
  - php7.0-zip          # For multiple attachments download
